# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
SCREEN_COLOR = (0, 0, 0)


# Grid
X_GRID = 300
Y_GRID = X_GRID
TILESIZE = min(SCREEN_WIDTH / X_GRID, SCREEN_HEIGHT / Y_GRID)
GRID_COLOR = (30, 0, 0)

# Food
FOOD_COLOR = (0, 255, 0)
FOOD_INITIAL_COUNT = 10000
FOOD_SPAWN_RATE = 10

# Microbes
MICROBE_COLOR = (0, 0, 255)
MICROBE_COUNT = 10
MICROBE_START_ENERGY = 50
MICROBE_ENERGY_LOSS_PER_TICK = 1
MICROBE_ENERGY_GAIN_PER_FOOD = 40
MICROBE_MAX_ENERGY = 1500
MICROBE_REPRODUCE_ENERGY = 1000